#Site 2 compose file
version: "3"

services:
  frontend:
    # build: ./src/frontend/
    image: vineethreddypati/finalfrontentuber2
    ports:
      - "80:3000"
    tty: true
    volumes:
      - ./uber-eats-frontend/src:/uber-eats-frontend/src
    networks:
      - common
    environment:
      PROD: 1
      BACKEND_HOST: backend
    depends_on:
      - backend

  backend:
    # build: ./src/backend/
    image: vineethreddypati/backendhububer3
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/backend/src
    networks:
      - common
    environment:
      PROD: 1

networks:
  common:
    driver: bridge
